service: gp #name of your service
provider:
  name: aws #cloud provider
  runtime: nodejs14.x  #runtime language and version
  role: arn:aws:iam::075760899250:role/gp-dev-role-lambda
  region: us-west-2  # cloud provider region where service deploys and resides. choose your preferred region
  vpc:
    securityGroupIds:
      - sg-039f695330a7ff22b
    subnetIds:
      - subnet-0bc84240d9e03925c
      - subnet-036d8e82f0dc9003a
functions:
  cognito-pretokengeneration:
    handler: dist/src/lambdas/PreTokenGeneration.handler #Reference to file handler.js & exported function 'write'
    environment:
      NODE_ENV: dev
      LOG_LEVEL: error
      DB_USER: gp-user
      DB_NAME: grepin
      DB_HOST: 
      DB_PASSWORD: 
    layers:
      - { Ref: CommonLambdaLayer }
    package:
      individually: true
      patterns:
        - '!./**'
        - 'dist/**'
        - '!dist/src/lambdas'
        - 'dist/src/lambdas/PreTokenGeneration.js'
  # CST-PreSignUpLambda:
  #   handler: dist/src/lambdas/PreSignUp.handler #Reference to file handler.js & exported function 'write'
  #   environment:
  #     NODE_ENV: dev
  #   layers:
  #     - { Ref: CommonLambdaLayer }
  #   package:
  #     individually: true
  #     patterns:
  #       - '!./**'
  #       - 'dist/**'
  #       - '!dist/src/lambdas'
  #       - 'dist/src/lambdas/PreSignUp.js'
layers:
  Common:
    path: dependencies # required, path to layer contents on disk
    name: Common # optional, Deployed Lambda layer name
    description: contains common node dependencies # optional, Description to publish to AWS
    compatibleRuntimes: # optional, a list of runtimes this layer is compatible with
      - nodejs14.x
    licenseInfo: MIT # optional, a string specifying license information  
    retain: false # optional, false by default. If true, layer versions are not deleted as new ones are created